name: Build & push Docker image on release

on:
  release:
    types: [published, prereleased]   # fire on releases and prereleases
  workflow_dispatch:                  # manual trigger if needed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: |
          IMAGE_TAG=${{ github.event.release.tag_name }}     # e.g. v1.2.3
          IMAGE_NAME=osprey-bids:$IMAGE_TAG
          docker build -f Dockerfile -t "$IMAGE_NAME" .

      - name: Push image
        run: |
          docker push my-image-name:${{ github.event.release.tag_name }}
