name: Build Docker image for tags

on:
  push:
    tags:
      - '*'        # run on every tag (e.g. v1.0.0, 2025-07-14, etc.)
  workflow_dispatch:  # allows manual runs from the Actions tab

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # ── Optional: log in if you want to push the image ─────────────
       - name: Log in to Docker Hub
         uses: docker/login-action@v3
         with:
           username: ${{ secrets.DOCKERHUB_USERNAME }}
           password: ${{ secrets.DOCKERHUB_TOKEN }}
       ────────────────────────────────────────────────────────────────

      - name: Build Docker image
        run: |
          IMAGE_TAG=${{ github.ref_name }}         # e.g. v1.2.3
          IMAGE_NAME=my-image-name:$IMAGE_TAG
          docker build -f Dockerfile -t $IMAGE_NAME .

      # ── Optional: push the image to Docker Hub (or any registry) ───
       - name: Push image
         run: docker push my-image-name:${{ github.ref_name }}
      # ────────────────────────────────────────────────────────────────
