name: Build Docker image for tags

on:
  push:
    release:
      types: [created]          # run on every tag push
  workflow_dispatch:  # allow manual runs

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: |
          IMAGE_TAG=${{ github.ref_name }}    # e.g. v1.2.3
          IMAGE_NAME=my-image-name:$IMAGE_TAG
          docker build -f Dockerfile -t $IMAGE_NAME .

      - name: Push image
        run: docker push my-image-name:${{ github.ref_name }}
